Repository hassio-addons/bashio, pull requests merged in 2021-01, with the labels that each got.

#42 Add Docker & Operating System info properties
  lib/info.sh
Labels: new-feature

#43 Replace update available logic with property access
  lib/cli.sh
  lib/core.sh
Labels: enhancement

#44 Add core rebuild command
  lib/core.sh
Labels: new-feature

#45 Add Observer support
  lib/observer.sh
Labels: new-feature

#46 Add boot property of operating system info
  lib/os.sh
Labels: new-feature

#47 Fix and improve update_available logic for all plugins
  lib/addons.sh
  lib/audio.sh
  lib/core.sh
  lib/dns.sh
  lib/os.sh
  lib/supervisor.sh
Labels: enhancement

#48 Fix caching API response caching bug
  lib/core.sh
  lib/info.sh
  lib/os.sh
Labels: bugfix

#49 Add disk stats to host endpoint
  lib/host.sh
Labels: new-feature

#50 Add usb property to hardware endpoint
  lib/hardware.sh
Labels: new-feature

#51 Upgrade Code of Conduct
  CODE_OF_CONDUCT.md
Labels: maintenance

#52 Update license and documentation
  LICENSE.md
  README.md
Labels: maintenance

#53 Fix pipeline badges
  README.md
Labels: documentation

#54 Fix slug: unbound variable in addon.update_available
  lib/addons.sh
Labels: bugfix

#55 Initial support for Network commands
  lib/bashio.sh
  lib/network.sh
Labels: new-feature

#57 Allow to edit add-on options
  lib/addons.sh
Labels: new-feature
