Repository hassio-addons/bashio, pull requests merged in 2021-11, with the labels that each got.

#82 Fetch config from API
  lib/bashio.sh
  lib/config.sh
  lib/const.sh
Labels: no-stale

#86 Allow fetching configuration parameters with a default value
  lib/config.sh
Labels: new-feature

#89 Fix shellcheck warnings
  lib/api.sh
  lib/pwned.sh
Labels: bugfix

#90 Fix default value handling for configuration options
  lib/config.sh
Labels: bugfix

#91 Fix processing of empty add-on config
  lib/addons.sh
Labels: bugfix
