Repository hassio-addons/bashio, pull requests merged in 2021-02, with the labels that each got.

#58 Using new cache location
  lib/const.sh
Labels: enhancement

#60 Put Bashio cache folder in a dot folder inside tmp
  lib/const.sh
Labels: enhancement

#64 📚 Minor typos
  lib/config.sh
Labels: documentation

#61 Remove deprecated hardware trigger method
  lib/hardware.sh
Labels: breaking-change

#66 Add new add-on options from Supervisor 2021.2
  lib/addons.sh
Labels: breaking-change, new-feature
