Repository hassio-addons/bashio, pull requests merged in 2023-05, with the labels that each got.

#104 Allow multiple lines in var.json
  lib/var.sh
Labels: stale

#133 Adjust shellcheck warnings
  lib/const.sh
  lib/network.sh
Labels: maintenance

#134 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
Labels: maintenance

#135 Spelling and grammar fixes
  lib/addons.sh
  lib/api.sh
  lib/audio.sh
  lib/bashio
  lib/bashio.sh
  lib/cache.sh
  lib/cli.sh
  lib/color.sh
  lib/config.sh
  lib/const.sh
  lib/core.sh
  lib/debug.sh
  lib/discovery.sh
  lib/dns.sh
  lib/exit.sh
  lib/fs.sh
  lib/hardware.sh
  lib/host.sh
  lib/info.sh
  lib/jq.sh
  lib/log.sh
  lib/multicast.sh
  lib/net.sh
  lib/network.sh
  lib/observer.sh
  lib/os.sh
  lib/pwned.sh
  lib/repositories.sh
  lib/services.sh
  lib/string.sh
  lib/supervisor.sh
  lib/var.sh
Labels: enhancement
